# Generated by Django 4.1.4 on 2023-01-06 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=20)),
                ('house_teacher', models.CharField(max_length=35)),
                ('student_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=40)),
                ('student_id', models.IntegerField()),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('classtable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentdata.classtable')),
            ],
        ),
    ]
